# -*- coding: utf-8 -*-
"""data_gen.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5_lNj34FfiavhvXGhZ0JPPBG7944iBS
"""

# data_gen.py – Dataset sintetico di ticket

import pandas as pd  #importo la libreria Pandas
import random        #importo le funzioni random per creare in modo casuale i ticket

# Imposto il numero di ticket
NUM_TICKETS = 300

# Liste di possibili categorie e priorità
categorie = ["Amministrativo", "Tecnico", "Commerciale"]
priorita = ["Bassa", "Media", "Alta"]

# Alcune frasi di base per generare i titoli e le descrizioni
titoli_base = [
    "Problema con", "Richiesta di", "Errore durante", "Aggiornamento su",
    "Verifica di", "Domanda su", "Segnalazione per", "Assistenza su"
]

oggetti = [
    "fattura", "rete aziendale", "accesso al portale", "software gestionale",
    "ordine cliente", "stampante", "licenza scaduta", "pagamento", "contratto", "email aziendale"
]

descrizioni_base = [
    "Si è verificato un problema durante l'utilizzo di",
    "È necessaria assistenza per",
    "Il sistema segnala un errore relativo a",
    "Richiesta di informazioni aggiuntive su",
    "Bisogna risolvere un malfunzionamento legato a"
]

# Mi creo una funzione per creare ticket in modo casuale
def genera_ticket(idx):
    titolo = f"{random.choice(titoli_base)} {random.choice(oggetti)}" #genero in modo casuale il titolo del problema tra le liste di titoli e oggetti
    descrizione = f"{random.choice(descrizioni_base)} {random.choice(oggetti)}." #faccio lo stesso per generarmi una descrizione in modo casuale
    categoria = random.choice(categorie)     #in modo casuale faccio sciegliere la categoria
    priorita_ticket = random.choices(priorita, weights=[0.4, 0.4, 0.2])[0]  # in modo casuale faccio scegliere anche la priorità, più probabile bassa/media
    return [idx, titolo, descrizione, categoria, priorita_ticket]

# Genero i ticket
dataset = [genera_ticket(i+1) for i in range(NUM_TICKETS)]

# Creo il DataFrame
df = pd.DataFrame(dataset, columns=["id", "titolo", "descrizione", "categoria", "priorita"])

# Salvo su file CSV
df.to_csv("synthetic_tickets.csv", index=False, encoding="utf-8")

print("Dataset creato con successo!")  #visualizzo il dataset come prova
df.head(10)

import pandas as pd

df = pd.read_csv("synthetic_tickets.csv", encoding="utf-8")

# Dimensioni del dataset
print("Shape:", df.shape)

# Controllo valori nulli
print("Nulls per colonna:\n", df.isnull().sum())

# Bilanciamento classi (categorie e priorità)
print("\nDistribuzione categorie:\n", df['categoria'].value_counts(normalize=True))
print("\nDistribuzione priorità:\n", df['priorita'].value_counts(normalize=True))

# Controllo duplicati
print("\nNumero duplicati (tutte le colonne):", df.duplicated().sum())